name: Build and Publish Docker Image

on:
  pull_request:
    branches:
      - dev
      - qa
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        run: docker build -t ghcr.io/testdevops24/test-front/my-app:latest ./holagoomba

      - name: Push the Docker image
        run: docker push ghcr.io/testdevops24/test-front/my-app:latest
